apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.apps_Deployment: |
    discovery.lua: |
      actions = {}
      actions["ScaleToZero"] = {}
      actions["restart"] = {}
      return actions
    definitions:
    - name: ScaleToZero
      action.lua: |
        if obj.spec.replicas > 0 then
        obj.spec.replicas = 0
        end
        return obj
    - name: restart
      # Lua Script to modify the obj
      action.lua: |
        local os = require("os")
        if obj.spec.template.metadata == nil then
            obj.spec.template.metadata = {}
        end
        if obj.spec.template.metadata.annotations == nil then
            obj.spec.template.metadata.annotations = {}
        end
        obj.spec.template.metadata.annotations["kubectl.kubernetes.io/restartedAt"] = os.date("!%Y-%m-%dT%XZ")
        return obj
