apiVersion: v1
kind: Namespace
metadata:
  name: certorigin
  labels:
    app: kubed # Define namespace label for kubed
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testcert
  namespace: certorigin
spec:
  secretName: origin-tls
  commonName: test.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "app=kubed" # Sync certificate to matching namespaces
